/**
 * The subset of the Anchor IDL spec (0.1.0) these programs actually use.
 *
 * This file is a *type*, not data. The data is in `src/idl/`, generated by
 * `anchor build` and copied by `scripts/sync-idl.mjs`; typing it here means an
 * IDL feature the coder cannot handle — a generic, an aliased type, a
 * `program`-qualified PDA — fails the typecheck rather than reaching the coder
 * and producing a plausible wrong byte string.
 *
 * That is the whole reason the shape is written out narrowly instead of as
 * `unknown`. A permissive type would compile against anything and defer the
 * problem to the moment a user signs.
 */

// ---------------------------------------------------------------------- types

/** Anchor's primitive type names, spelled as they appear in the IDL. */
export type IdlPrimitive =
  | "bool"
  | "u8"
  | "i8"
  | "u16"
  | "i16"
  | "u32"
  | "i32"
  | "u64"
  | "i64"
  | "u128"
  | "i128"
  | "f32"
  | "f64"
  | "string"
  | "pubkey"
  | "bytes";

export type IdlType =
  | IdlPrimitive
  | { defined: { name: string } }
  | { option: IdlType }
  | { vec: IdlType }
  | { array: [IdlType, number] };

export interface IdlField {
  name: string;
  docs?: string[];
  type: IdlType;
}

export interface IdlEnumVariant {
  name: string;
  docs?: string[];
  /** Absent for a unit variant. Named fields only; tuple variants are unused. */
  fields?: IdlField[];
}

export type IdlTypeDefKind =
  | { kind: "struct"; fields?: IdlField[] }
  | { kind: "enum"; variants: IdlEnumVariant[] };

export interface IdlTypeDef {
  name: string;
  docs?: string[];
  type: IdlTypeDefKind;
}

// --------------------------------------------------------------- instructions

/**
 * One seed of a PDA, as the IDL describes it.
 *
 * `const` carries literal bytes. `account` names either an account in the same
 * instruction (`"pool"`) or a *field of* one (`"pool.stake_mint"`) — the latter
 * cannot be derived from the instruction alone and has to be supplied. `arg`
 * names one of the instruction's own arguments.
 */
export interface IdlSeed {
  kind: "const" | "account" | "arg";
  value?: number[];
  path?: string;
  account?: string;
}

export interface IdlPda {
  seeds: IdlSeed[];
}

export interface IdlInstructionAccount {
  name: string;
  docs?: string[];
  writable?: boolean;
  signer?: boolean;
  optional?: boolean;
  /** A fixed address, e.g. the system program. */
  address?: string;
  pda?: IdlPda;
  relations?: string[];
}

export interface IdlInstruction {
  name: string;
  docs?: string[];
  discriminator: number[];
  accounts: IdlInstructionAccount[];
  args: IdlField[];
}

// ---------------------------------------------------------------------- root

export interface IdlDiscriminated {
  name: string;
  discriminator: number[];
}

export interface IdlErrorDef {
  code: number;
  name: string;
  msg?: string;
}

export interface Idl {
  address: string;
  metadata: {
    name: string;
    version: string;
    spec: string;
    description?: string;
    repository?: string;
  };
  instructions: IdlInstruction[];
  accounts?: IdlDiscriminated[];
  events?: IdlDiscriminated[];
  errors?: IdlErrorDef[];
  types?: IdlTypeDef[];
}

// -------------------------------------------------------------------- lookups

/**
 * Lookups throw rather than returning `undefined`.
 *
 * Every caller here passes a name that is either present in the IDL or a typo,
 * and a typo that yields `undefined` becomes a missing account or an empty
 * discriminator several frames later. Failing at the lookup names the mistake.
 */

export function instruction(idl: Idl, name: string): IdlInstruction {
  const found = idl.instructions.find((i) => i.name === name);
  if (!found) {
    throw new Error(
      `${idl.metadata.name} has no instruction "${name}" — it declares: ` +
        idl.instructions.map((i) => i.name).join(", "),
    );
  }
  return found;
}

export function typeDef(idl: Idl, name: string): IdlTypeDef {
  const found = idl.types?.find((t) => t.name === name);
  if (!found) throw new Error(`${idl.metadata.name} has no type "${name}"`);
  return found;
}

export function accountDiscriminator(idl: Idl, name: string): Uint8Array {
  const found = idl.accounts?.find((a) => a.name === name);
  if (!found) throw new Error(`${idl.metadata.name} declares no account "${name}"`);
  return Uint8Array.from(found.discriminator);
}
